ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name="cart"

urlpatterns = [
    path('addtocart/<int:i>/',views.addtocart,name="addtocart"),
    path('cart',views.cart_view,name="cart"),
    path('cart_remove/<int:i>/',views.cart_remove,name="cart_remove"),
    path('delete/<int:i>/',views.delete,name="delete"),
    path('orderform',views.orderform,name="orderform"),
    path('status/<u>',views.payment_status,name="status"),
    path('orderview',views.order_view,name="orderview")
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name="search"

urlpatterns = [
    path('search',views.search_products,name="search"),
]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"

urlpatterns = [
    path('',views.categories,name="categories"),
    path('products/<int:p>',views.products,name="products"),
    path('details/<int:p>',views.details,name="details"),
    path('register', views.register, name="register"),
    path('login', views.user_login, name="login"),
    path('logout',views.user_logout,name="logout"),
    path('addcategory', views.addcategory, name="addcategory"),
    path('addproduct',views.addproduct,name="addproduct"),
    path('addstock/<int:i>',views.addstock,name="addstock"),
]

ecommerce/cart/models.py
from django.db import models
from shop.models import Product

from django.contrib.auth.models import User


# Create your models here.
class Cart(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    date_added=models.DateTimeField(auto_now_add=True)

    def subtotal(self):
        return self.quantity*self.product.price


class Payment(models.Model):
    name=models.CharField(max_length=30)
    amount=models.IntegerField()
    order_id=models.CharField(max_length=30,blank=True)  #blank true means if we do not enter any data to this fied there iss no prbm wiil happen
    razorpay_payment_id=models.CharField(max_length=30,blank=True)
    paid=models.BooleanField(default=False)

class Order_details(models.Model):

    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    address=models.TextField()
    phone_no=models.BigIntegerField()
    pin=models.IntegerField()

    order_id=models.CharField(max_length=30,blank=True)
    ordered_date=models.DateTimeField(auto_now_add=True)

    payment_status=models.CharField(max_length=20,default="pending")
    delivery_status=models.CharField(max_length=20,default="pending")

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/views.py
import razorpay
from django.shortcuts import render,redirect
from shop.models import Product
from cart.models import Cart,Payment,Order_details
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User

# Create your views here.
@login_required
def addtocart(request,i):
    p=Product.objects.get(id=i)
    u=request.user

    try:                                                #If a particular product for a particular user already exits
        c=Cart.objects.get(product=p,user=u)
        if(p.stock>0):
            c.quantity+=1
            c.save()
            p.stock-=1
            p.save()
    except:                                             #if particular record does not exist
       if(p.stock>0):
            c=Cart.objects.create(product=p,user=u,quantity=1)
            c.save()
            p.stock-=1
            p.save()

    return redirect('cart:cart')

def cart_view(request):
    u=request.user
    total=0

    c=Cart.objects.filter(user=u)
    total=0
    for i in c:
        total+=i.quantity*i.product.price

    context={'cart':c,'total':total}
    return render(request,'cart.html',context)

@login_required
def cart_remove(request,i):
    p=Product.objects.get(id=i)
    u=request.user

    try:                                                #If a particular product for a particular user already exits
        c=Cart.objects.get(product=p,user=u)
        if(c.quantity >1):
            c.quantity-=1
            c.save()
            p.stock+=1
            p.save()

        else:
            c.delete()
            p.stock +=1
            p.save()

    except:
        pass

    return redirect('cart:cart')

@login_required
def delete(request,i):
    p = Product.objects.get(id=i)
    u = request.user

    try:
        c = Cart.objects.get(product=p, user=u)
        c.delete()
        p.stock += c.quantity
        p.save()

    except:
        pass

    return redirect('cart:cart')
@login_required
def orderform(request):
    if(request.method=="POST"):
        address=request.POST['a']
        phone=request.POST['pn']
        pin=request.POST['p']
        u=request.user
        c=Cart.objects.filter(user=u)
        total=0
        for i in c:
            total+=i.quantity*i.product.price
        total1=int(total*100)
      


        client=razorpay.Client(auth=('rzp_test_OrPSKIbnVhJEFd','6evKSZ2OWGi9dIu2SEowiOzc'))     #creates a client connection using razorpay id and secret code

        response_payment=client.order.create(dict(amount=total1,currency="INR")) #CREATES an order id with razorpay using razorpay client

        print(response_payment)

        order_id=response_payment['id']       #Retrieves the order_id from response
        status=response_payment['status']     #retrieves status from response

        if(status == 'created'): #if status is created then store order_id in Payment and Order_details table
            p=Payment.objects.create(name=u.username,amount=total,order_id=order_id)
            p.save()
            for i in c:      #for each item creates a record inside Order_details table
                o=Order_details.objects.create(product=i.product,user=u,no_of_items=i.quantity,address=address,phone_no=phone,pin=pin,order_id=order_id)
                o.save()

        response_payment['name']=u.username
        context={'payment':response_payment}
        return render(request,'payment.html',context)

    return render(request,'orderform.html')

from django.contrib.auth import login
@csrf_exempt
def payment_status(request,u):
    usr = User.objects.get(username=u)
    if not request.user.is_authenticated:
        login(request,usr)

    if (request.method == "POST"):
        response=request.POST
        print(response)

        param_dict={
            'razorpay_order_id':response['razorpay_order_id'],
            'razorpay_payment_id':response['razorpay_payment_id'],
            'razorpay_signature':response['razorpay_signature']
        }
        client = razorpay.Client(auth=('rzp_test_OrPSKIbnVhJEFd', '6evKSZ2OWGi9dIu2SEowiOzc'))
        print(client)
        try:
            status=client.utility.verify_payment_signature(param_dict) #to check the authenticity of the razorpay signature
            print(status)

            #To retrieve a particular record from Payment Table matching with razorpay response order id
            p=Payment.objects.get(order_id=response['razorpay_order_id'])
            p.razorpay_payment_id=response['razorpay_payment_id']
            p.paid=True
            p.save()

            #to retrieves  a record from Order_details Table matching with raxorpay response order id
            o=Order_details.objects.filter(order_id=response['razorpay_order_id'])
            for i in o:
                i.payment_status="completed"
                i.save()

            #after payment delete particular record from carts
            c=Cart.objects.filter(user=usr) #filter all records matching with particular user
            c.delete()
        except:
            pass

    return render(request,'payment_status.html',{'status':status})


@login_required
def order_view(request):
    u=request.user
    o=Order_details.objects.filter(user=u)
    print(o)
    context={'orders':o}
    return render(request,'orderview.html',context)

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q
# Create your views here.



def search_products(request):
    p = None
    query= ""
    if(request.method=="POST"):
        query=request.POST.get('q')  #READS THE QUERY VALUE
        if query:
            p=Product.objects.filter(Q(name__icontains=query) | Q(desc__icontains=query))  #FILTER THE RECORDS MATCHING WITH QUERY
    context={'pro':p,'query':query}
    return render(request,'search.html',context)

ecommerce/templates/addcategory.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container m-3">

  <div class="border border-1 shadow  py-2" style="width:100%; margin-right:20px; margin-left:60px;">


<h2 class="text-center mt-3">Add Category Details</h2>

<div class="container px-2 mb-5">
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
    <div class="mb-3">
      <label  class="form-label">Name</label>
      <input type="text" class="form-control" name="n" placeholder="Enter Category name">
    </div>

<div class="mb-3">
  <label  class="form-label">Image</label>
  <input type="file" class="form-control" name="i">
</div>


        <div class="mb-3">
            <label class="form-label">Description</label>
            <textarea class="form-control" rows="3" name="de" placeholder="Write Category Description"></textarea>
        </div>



      <div class="mb-3">
        <input type="submit" class="form-control">
      </div>
    </form>
</div>
  </div>
</div>



{% endblock %}

ecommerce/templates/addstock.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container m-3">

  <div class="border border-1 shadow  py-2" style="width:50%; margin-right:200px; margin-left:340px; margin-top:60px;">


<h2 class="text-center mt-3">Add Stock Details</h2>
      <div class="container px-2 mb-5">

       <form method="POST">
      {% csrf_token %}
    <div class="mb-3">
      <label  class="form-label"></label>
      <input type="number" name="s" value="{{pro.stock}}" class="form-control">
    </div>

            <div class="mb-3">
        <input type="submit" class="form-control">
      </div>
    </form>
      </div>



  </div>
</div>


{% endblock %}

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ashion Template">
    <meta name="keywords" content="Ashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My Shop</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cookie&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap"
    rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Offcanvas Menu Begin -->
    <div class="offcanvas-menu-overlay"></div>
    <div class="offcanvas-menu-wrapper">
        <div class="offcanvas__close">+</div>
        <ul class="offcanvas__widget">
            <li><span class="icon_search search-switch"></span></li>
            <li><a href="#"><span class="icon_heart_alt"></span>
                <div class="tip">2</div>
            </a></li>
            <li><a href="#"><span class="icon_bag_alt"></span>
                <div class="tip">2</div>
            </a></li>
        </ul>
        <div class="offcanvas__logo">
            <a href="./index.html"><img src="{% static 'img/logo.png' %}" alt=""></a>
        </div>
        <div id="mobile-menu-wrap"></div>
        <div class="offcanvas__auth">
            <a href="#">Login</a>
            <a href="#">Register</a>
        </div>
    </div>
    <!-- Offcanvas Menu End -->

    <!-- Header Section Begin -->


    <header class="header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-xl-3 col-lg-2">
                    <div class="header__logo">
                        <a href="./index.html"><img src="{% static 'img/logo.png' %}" alt=""></a>
                    </div>
                </div>
                <div class="col-xl-6 col-lg-7">
                    <nav class="header__menu">

                        <ul class="">
                            <li class="active"><a href="{%url 'shop:categories' %}">Home</a></li>

                            <li><a href="#">All-Categories</a>
                                    <ul class="dropdown">
                                        {% for i in links %}
                                        <li><a href="{% url 'shop:products' i.id %}">{{i.name}}</a></li>
                                        {% endfor %}
                                    </ul>
                                </li>
                                    {% if user.is_authenticated %}
                                    {% if user.is_superuser == False %}

                                    <li><a href="{%url 'cart:orderview' %}">Your_Orders</a></li>
<!--                                    <li><a href="#">Blog</a></li>-->
<!--                                    <li><a href="#">Contact</a></li>-->
                             <li>
                                        <a href="{%url 'cart:cart' %}"><span class="icon_bag_alt"></span><sup class="mx-2 fs-5">{{c}}</sup></a>
                                    </li>
                                    {% else %}
                                   <li>
                                       <a href="{% url 'shop:addcategory' %}">Add-Cat</a>
                                   </li>
                                     <li>
                                       <a href="{% url 'shop:addproduct' %}">Add-Prod</a>
                                   </li>
                                  {% endif %}
                                    <li><a href="{%url 'shop:logout' %}">Logout</a></li>


                            <ul class="header__right__widget">
                                <li><a href="{% url 'search:search' %}"><span class="icon_search search-switch"></span></a></li>
                            <li><a href="#"><span class="icon_heart_alt"></span>
                            </a></li>

                        </ul>
<!--                            -->
<!--                                <ul class="header__right__widget">-->
<!--                                  <form class="d-flex">-->
<!--                                      {% csrf_token %}-->
<!--                                      <input class="form-control me-1 border border-dark" type="search" placeholder="Search" aria-label="search">-->
<!--                                      <button class="btn btn-outline-dark" type="submit">Search</button>-->
<!--                                  </form>-->
<!--                        </ul>-->
                        </ul>

                            {% else %}


                    </nav>
                </div>

            <div class="col-lg-3 ">
                    <div class="header__right ">
                        <div class="header__right__auth">
                            <a href="{%url 'shop:login' %}">Login</a>
                            <a href="{%url 'shop:register' %}">Register</a>
                        </div>

                         <ul class="header__right__widget">
                             <li><a href="{%url 'search:search' %}"><span class="icon_search search-switch"></span></a></li>
                            <li><a href="#"><span class="icon_heart_alt"></span>

                            </a></li>

                        </ul>

<!--                        <ul class="header__right__widget">&ndash;&gt;-->
<!--                                  <form class="d-flex">-->
<!--                                      {% csrf_token %}-->
<!--                                      <input class="form-control me-1 border border-dark" type="search" placeholder="Search" aria-label="search">-->
<!--                                      <button class="btn btn-outline-dark" type="submit">Search</button>-->
<!--                                  </form>-->
<!--                       </ul>-->

                    </div>
                </div>

            </div>
            <div class="canvas__open">
                <i class="fa fa-bars"></i>
            </div>
        </div>
            {% endif %}
    </header>

{% block content %}

{% endblock %}
<!-- Footer Section Begin -->
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-6 col-sm-7">
                <div class="footer__about">
                    <div class="footer__logo">
                        <a href="./index.html"><img src="{% static 'img/logo.png' %}" alt=""></a>
                    </div>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
                    cilisis.</p>
                    <div class="footer__payment">
                        <a href="#"><img src="{% static 'img/payment/payment-1.png' %}" alt=""></a>
                        <a href="#"><img src="{% static 'img/payment/payment-2.png' %}" alt=""></a>
                        <a href="#"><img src="{% static 'img/payment/payment-3.png' %}" alt=""></a>
                        <a href="#"><img src="{% static 'img/payment/payment-4.png' %}" alt=""></a>
                        <a href="#"><img src="{% static 'img/payment/payment-5.png' %}" alt=""></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-3 col-sm-5">
                <div class="footer__widget">
                    <h6>Quick links</h6>
                    <ul>
                        <li><a href="#">About</a></li>
                        <li><a href="#">Blogs</a></li>
                        <li><a href="#">Contact</a></li>
                        <li><a href="#">FAQ</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-3 col-sm-4">
                <div class="footer__widget">
                    <h6>Account</h6>
                    <ul>
                        <li><a href="#">My Account</a></li>
                        <li><a href="#">Orders Tracking</a></li>
                        <li><a href="#">Checkout</a></li>
                        <li><a href="#">Wishlist</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-md-8 col-sm-8">
                <div class="footer__newslatter">
                    <h6>NEWSLETTER</h6>
                    <form action="#">
                        <input type="text" placeholder="Email">
                        <button type="submit" class="site-btn">Subscribe</button>
                    </form>
                    <div class="footer__social">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-youtube-play"></i></a>
                        <a href="#"><i class="fa fa-instagram"></i></a>
                        <a href="#"><i class="fa fa-pinterest"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                <div class="footer__copyright__text">
                    <p>Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a></p>
                </div>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </div>
        </div>
    </div>
</footer>
<!-- Footer Section End -->

<!-- Search Begin -->
<div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch">+</div>
        <form class="search-model-form">
            <input type="text" id="search-input" placeholder="Search here.....">
        </form>
    </div>
</div>
<!-- Search End -->

<!-- Js Plugins -->
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/mixitup.min.js' %}"></script>
<script src="{% static 'js/jquery.countdown.min.js' %}"></script>
<script src="{% static 'js/jquery.slicknav.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.nicescroll.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>

</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5 " style="margin-bottom:100px;">
    <h6 class="text-center"><strong>Shopping Cart</strong></h6>
    <p></p>
<div class="row">

    <div class="col-7">
        <table class="table table-bordered table-primary text-center">
            <tr><th colspan="7">Cart Items</th></tr>

            {% for i in cart %}

            <tr>
                <td><img src="{{i.product.image.url}}" height="100px" width="100px"></td>
                <td>Product Name:{{i.product.name}}</td>
                <td>Quantity:{{i.quantity}}<br>
                unit price:{{i.product.price}}</td>
                <td>Subtotal:{{i.subtotal}}</td>
<td>
                {% if i.product.stock > 0 %}
                <a href="{% url 'cart:addtocart' i.product.id %}"><i class="fa fa-plus-circle text-dark" aria-hidden="true"></i></a>
                    <a href="{% url 'cart:cart_remove' i.product.id %}"><i class="fa fa-minus-circle text-dark" aria-hidden="true"></i></a>
                    <a href="{%url 'cart:delete' i.product.id %}"><i class="fa fa-trash text-dark" aria-hidden="true"></i></a>
                     {% else %}
                    <a href="{% url 'cart:cart_remove' i.product.id %}"><i class="fa fa-minus-circle text-dark" aria-hidden="true"></i></a>
                    <a href="{%url 'cart:delete' i.product.id %}"><i class="fa fa-trash text-dark" aria-hidden="true"></i></a>
                     {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>

    </div>
    <div class="col-4">
        <table class="table table-bordered table-primary text-center">
            <tr>
                <th>Check Out</th>
            </tr>
            <tr>
                <td>Total:{{total}}</td>
            </tr>
        </table>
        <div class="d-flex justify-content-between">
        <a href="{%url 'cart:orderform' %}" class="btn btn-primary">Place Order</a>
        <a href="" class="btn btn-primary">Continue Shopping</a>
        </div>
    </div>
</div>


</div>
</div>

{% endblock %}

ecommerce/templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



<!--<div class="container m-5">-->

<!--  <div class="border border-1 shadow mx-auto py-2" style="width:80%;">-->
<div class="border border-1 shadow mx-auto py-2 card mb-3 mt-5 mx-auto p-4" style="max-width: 60%;">
  <div class="row g-0">
    <div class="col-md-4 p-2">
      <img src="{{product.image.url}}" class=" rounded-start" alt="..." height="300px" width="100%">
    </div>
    <div class="col-md-8 lh-lg ps-5">
      <div class="card-body mt-3">
        <p class=" fw-bold mb-3"><strong>Product_Name: {{product.name}}</strong></p>
        <p class="card-text"><strong>Price: </strong>{{product.price}}</p>
        <p class="card-text"><strong>Description: </strong>{{product.desc}}</p>
        <p class="card-text"><strong>Stock: </strong>{{product.stock}}</p>
<!--        <a href="{% url 'cart:addtocart' product.id  %}" class="btn btn-primary">Add To Cart</a>-->
        {% if user.is_superuser == True %}
        {% if product.stock > 0 %}
        <h5>Product In Stock</h5>
        <a href="{% url 'shop:addstock' product.id %}" class="btn btn-primary fw-bold mt-3 mb-2 text-center">Add Stock</a>
        {% else %}
         <h5 class="text-danger;">Product Out of Stock</h5>
        <a href="{% url 'shop:addstock' product.id %}" class="btn btn-primary fw-bold mt-3 mb-2 text-center">Add Stock</a>
        {% endif %}



        {% else %}
        {% if product.stock > 0 %}
        <a href="" class="btn border border-secondary rounded-pill px-4 py-2 mb-4 text-primary"><i class="fa fa-shopping-bag me-2 text-primary"></i> Add to cart</a>
        {% else %}
        <h5>Out of Stock</h5>
        {% endif %}


        {% endif %}
      </div>
    </div>
  </div>
</div>


{% endblock %}

ecommerce/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container m-3">

  <div class="border border-1 shadow  py-2" style="width:100%; margin-right:20px; margin-left:60px;">


    <div class="container px-2 mb-5">
  <h2 class="text-center mt-3">LOGIN</h2>
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
<div class="mb-3">
  <label  class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Username">
</div>

<div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Password">
</div>



  <div class="mb-3">
    <input type="submit" class="form-control">
  </div>

</div>



  </div>
</div>
{% endblock %}

ecommerce/templates/payment_status.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

 <div class="container mt-5 p-5 bg-light w-50" style="margin-bottom:100px;">
     {% if status == True %}
     <h2 class="text-center">Payment Successful</h2>
     {% else %}
     <h2>Payment Failed,Try again Later</h2>
     {% endif %}
 </div>
{% endblock %}
</body>
</html>

ecommerce/templates/products.html
{% extends 'base.html' %}

{% block content %}


<div class="container">
    <img class="m-5" src="{{cat.image.url}}" height="400px" width="100%">
</div>
<h1 class="text-center mt-3 ">{{cat.name}}</h1>
<p class="text-center " style="text-align:justify;line-height:2; margin:100px;">{{cat.description}}</p>
<div class="row">

 {% for i in product %}

    <div class="col-sm-4 mb-3 ">
    <div class="card mx-auto border border-3 border-Light " style="width:250px;">
    <img src="{{i.image.url}}" height="200px" width="250px" class="card-ing-top" alt="">
    <div class="card-body text-center">
    <h5 class="card-title mb-3">{{i.name}}</h5>
    <h5  class="card-title mb-3"><i class="fa fa-inr" aria-hidden="true"></i>{{i.price}}</h5>
    <a href="{% url 'shop:details' i.id %}" class="btn btn-primary px-5 mb-2 fs-5">Details</a>

</div>

</div>
    </div>
  {% endfor %}
</div>
{% endblock %}

ecommerce/templates/search.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if pro == None %}
<div class="container mt-5 p-3 border border-3 border-Light shadow" style="...">
    <form class="d-flex" method="POST"  action="{% url 'search:search' %}">
         {% csrf_token %}
        <input class="form-control me-2 border border-dark" type="search" name="q" placeholder="search" aria-label="search">
        <button class="btn btn-outline-dark" type="submit">Search</button>
    </form>
</div>
{% else %}
<div class="container mt-5 p-3 border border-3 border-Light shadow text-center fst-italic" style="..">
    <h3 class="fst-italic">You have searched for {{query}}</h3></div>
    <div class="row">

 {% for i in pro %}

    <div class="col-sm-4 p-3 ">
    <div class="card mx-auto border border-3 border-Light shadow p-5" style="width:250px;">
    <img src="{{i.image.url}}" height="200px" width="250px" class="card-img-top" alt="">
    <div class="card-body text-center">
    <h5 class="card-title mb-3">{{i.name}}</h5>
    <h5  class="card-title mb-3"><i class="fa fa-inr" aria-hidden="true"></i>{{i.price}}</h5>
    <a href="{% url 'shop:details' i.id %}" class="btn btn-primary  mb-2 fs-5">Details</a>

</div>

</div>
    </div>
        {% empty %}
               <div>
            <h3 class="text-center">No Results Found</h3></div>
  {% endfor %}
</div>
</div>
{% endif %}

{% endblock %}